version: "2.1"
services:
  pgdb:
    build: db
    container_name: pgdb
    ports:
    - "5432:5432"

  redis:
    image: redis:4.0.14
    container_name: redis
    ports:
      - "6379:6379"
  
  nginx:
    build: nginx
    container_name: nginx
    ports:
    - "80:80"
    depends_on:
      - frontend
      - backend

  backend:
    build: backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - pgdb
      - redis
    command: ["./wait-for-it.sh", "pgdb:5432", "--", "sh", "./start.sh"]

  frontend:
    build: frontend
    container_name: frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
